BlogIt/BlogIt/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('accounts.urls')),
    path('blog/',include('blogs.urls')),
]

BlogIt/accounts/urls.py
from django.urls import path
from . views import SignUp,LogIn,LogOut

app_name = 'accounts'

urlpatterns = [
    path('',LogIn,name="login"),
    path('signup/',SignUp,name="signup"),
    path('logout/',LogOut,name="logout"),
]

BlogIt/blogs/urls.py
from django.urls import path
from . views import ListBlogs,PostBlog,BlogDetail,BlogDeleteConfirmation,BlogDelete,BlogUpdate

app_name = 'blogs'

urlpatterns = [
    path('',ListBlogs,name="list-blogs"),
    path('create-blog/',PostBlog,name="create-blog"),
    path('blog-detail/<int:pk>',BlogDetail,name="blog-detail"),
    path('blog-update/<int:pk>',BlogUpdate,name="blog-update"),
    path('blog-delete-confirmation/<int:pk>',BlogDeleteConfirmation,name="blog-delete-confirmation"),
    path('blog-delete/<int:pk>',BlogDelete,name="blog-delete"),
]

BlogIt/accounts/models.py
from django.db import models

# Create your models here.

BlogIt/blogs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Blog(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    
    def __str__(self):
        return self.title

BlogIt/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django import forms
from django.contrib.auth.models import User

class CreateUserForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class':"form-control"}))
    password1 = forms.CharField(label="password",widget=forms.PasswordInput(attrs={'class':"form-control"}))
    password2 = forms.CharField(label="confirm password",widget=forms.PasswordInput(attrs={'class':"form-control"}))

    class Meta:
        model = User
        fields =['username']

class LogInForm(AuthenticationForm):
    username = forms.CharField(label='username',widget=forms.TextInput(attrs={'class':'form-control'}))
    password = forms.CharField(label='password',widget=forms.PasswordInput(attrs={'class':'form-control'}))
    class Meta:
        model =User
        fiedls=['username','password']

BlogIt/blogs/forms.py
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django import forms
from . models import Blog

class CreateBlog(forms.ModelForm):
    title = forms.CharField(label="Title",error_messages={"required": "please fill it"},widget=forms.TextInput(attrs={"class":"form-control"}))
    content = forms.CharField(label="Content",error_messages={"required": "please fill it"},widget=forms.Textarea(attrs={"rows":5,"class":"form-control"}))
    class Meta:
        model = Blog
        fields =['title','content']

    def save(self, commit=True, user=None, *args, **kwargs):
        instance = super(CreateBlog, self).save(commit=False, *args, **kwargs)
        instance.user = user
        if commit:
            instance.save()
        return instance

BlogIt/accounts/views.py
from django.shortcuts import render,redirect,HttpResponseRedirect
from django.contrib.auth import authenticate,login,logout
from .forms import CreateUserForm,LogInForm
from django.contrib import messages
# Create your views here.



def SignUp(request):
    if request.user.is_authenticated:
        return redirect('/blog/')
    else:
        if request.method=="POST":
            form = CreateUserForm(request.POST)
            if form.is_valid():
                form.save()
                messages.success(request,'Account has been created successfully !')
        else:
            form = CreateUserForm()
        return render(request,'accounts/signup.html',{'form':form})

def LogIn(request):
    if request.user.is_authenticated:
        return redirect('blogs:list-blogs')
    else:
        if request.method=="POST":
            form=LogInForm(request=request,data=request.POST)
            if form.is_valid():
                username = form.cleaned_data['username']
                password = form.cleaned_data['password']
                user = authenticate(username=username,password=password)
                if user:
                    login(request,user)
                    messages.success(request,"Logged in successfully")
                    return HttpResponseRedirect('/blog/')
        else:
            form = LogInForm()
        return render(request,'accounts/login.html',{'form':form})

def LogOut(request):
    logout(request)
    return redirect('/')

BlogIt/blogs/views.py
from django.shortcuts import render,redirect,get_object_or_404
from . models import Blog
from . forms import CreateBlog

# Create your views here.
from django.contrib import messages
from django.contrib.auth.decorators import login_required 


@login_required
def ListBlogs(request):
    if request.user.is_superuser:
        blogs = Blog.objects.all()
    else:
        blogs = Blog.objects.filter(user=request.user)
    return render(request,'blogs/list.html',{"blogs":blogs})

@login_required
def PostBlog(request):
    if request.method=="POST":
        form = CreateBlog(request.POST)
        if form.is_valid():
            form.save(user=request.user)
            return redirect('/blog/')
    else:
        form = CreateBlog()
    
    return render(request,"blogs/post-blog.html",{"form":form})


@login_required
def BlogDetail(request,pk):
    if request.user.is_superuser:
        blogs = Blog.objects.get(pk=pk)
    else:
        blogs = Blog.objects.get(user=request.user,pk=pk)
    return render(request,'blogs/blog-detail.html',{"blog":blogs})

@login_required
def BlogUpdate(request,pk):
    blog = get_object_or_404(Blog,pk=pk)
    if request.method == "POST":
        form = CreateBlog(request.POST,instance=blog)
        if form.is_valid():
            form.save(user=request.user)
            messages.success(request,"Successfully updated")
    else:
        form = CreateBlog(instance=blog)
    return render(request,'blogs/updateblog.html',{"form":form})

@login_required
def BlogDeleteConfirmation(request,pk):
    blog = get_object_or_404(Blog,pk=pk)
    return render(request,'blogs/delete-confirmation.html',{"blog":blog})

@login_required
def BlogDelete(request,pk):
    blog = get_object_or_404(Blog,pk=pk)
    blog.delete()
    return redirect('/blog/')

BlogIt/templates/accounts/login.html
{% extends 'base.html'%}

{%block title %}
Login
{% endblock %}

{% block content %}
<form method="POST" novalidate>
    {% csrf_token %}

    <br>
    {% for field in form %}
    <div class="form-group">
        {{field.label_tag}}
        {{field}}
        {{field.errors|striptags}}
    </div>
    {% endfor %}
    <input type="submit" class="btn btn-primary" value="submit">
    <br><br>
    <!-- it will show default errors -->
    {% if form.non_field_errors %}
    {%for error in form.non_field_errors%}
    <span class="badge bg-warning text-dark">{{error}}</span>
    {%endfor%}
    {% endif %}
</form>
{% endblock %}

BlogIt/templates/accounts/signup.html
{% extends 'base.html' %}

{% block title %}
signup
{% endblock %}

{% block content %}
<form method="POST" novalidate>
    {% csrf_token %}
    {% for field in form %}
    <div class="form-group">
        {{field.label_tag}}
        {{field}}
        {{field.errors|striptags}}
    </div>
    {% endfor %}
    <input type="submit" class="btn btn-primary" value="submit">

</form>
{% if messages %}
{% for message in messages%}
<span class="badge bg-success">{{message}}</span>
<!-- <span {% if messages.tags %} class="badge badge-{{message.tags}}" {% endif %}>{{message}}</span> -->
{% endfor %}
{% endif %}
{%endblock%}

BlogIt/templates/base.html
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
        crossorigin="anonymous"></script>
        <title>
        {% block title %}
        {% endblock %}
        </title>
</head>

<body>

    {%include 'navbar.html' %}

    <div class="container" style="margin-top:20px;">
        {% block content %}
        {% endblock %}
    </div>
</body>

</html>

BlogIt/templates/blogs/blog-detail.html
{% extends 'base.html' %}

{% block title %}
Blog detail
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-sm-4">
        <div class="card">
            <div class="card-header">
              {{blog.created_at}}
            </div>
            <div class="card-body">
              <h5 class="card-title">{{blog.title}}</h5>
              <p class="card-text">{{blog.content}}</p>
              <a href="{% url 'blogs:blog-delete-confirmation' blog.id %}">delete</a>
              {%if not request.user.is_superuser%}
              <a href="{% url 'blogs:blog-update' blog.id %}">
                edit
              </a>
              {% endif %}
            </div>
          </div>
    </div>
</div>

{% endblock %}

BlogIt/templates/blogs/delete-confirmation.html
{% extends 'base.html' %}

{% block title %}
Delete Confirmation
{%endblock%}

{% block content %}
<span class="badge bg-danger">Are you sure you want to delete this blog</span>

<a href="{% url 'blogs:blog-delete' blog.id %}">Yes</a>

<a href="{% url 'blogs:blog-detail' blog.id %}">Cancel</a>
{%endblock%}

BlogIt/templates/blogs/list.html
{% extends 'base.html' %}

{% block title %}
All Blogs
{% endblock %}

{% block content %}

<div class="row">
  {% if blogs %}
  {% for blogs in blogs %}
    <div class="col-sm-4">
        <div class="card">
            <div class="card-header">
              {{blogs.created_at}}
            </div>
            <div class="card-body">
              <h5 class="card-title">{{blogs.title}}</h5>
              <p class="card-text">{{blogs.content|truncatechars:20}}....</p>
              <a href="{% url 'blogs:blog-detail' blogs.id %}">See More</a>
            </div>
          </div>
    </div>
    {% endfor %}
    {% else %}
    <div class="card">
      <div class="card-header">
        No Data Available , 
      </div>
      <div class="card-body">
        <h5 class="card-title">Seems That You Haven't Post Anything Yet</h5>
        <p class="card-text">click on the link below to make your first post</p>
        <a href="{% url 'blogs:create-blog' %}" class="btn btn-primary">Create a Blog</a>
      </div>
      {% endif %}
</div>


{% endblock %}

BlogIt/templates/blogs/post-blog.html
{% extends 'base.html' %}

{% block title%}
Create A Blog
{% endblock %}

{% block content %}
<div class="col-sm-10">
    <h3 class="text-white">Add New Post</h3>

    <div class="jumbotron jumbotron-fluid">
        <div class="container">
            <form method="POST">
                {% csrf_token %}
                <div class="row">
                    {{form.as_p}}
                    <button type="submit" class="btn btn-success">Send</button>
            </form>
        </div>
    </div>
    {% if messages %}
    {% for message in messages%}
    <span class="alert alert-success">{{message}}</span>
    {% endfor %}
    {% endif %}
</div>
{% endblock %}

BlogIt/templates/blogs/updateblog.html
{% extends 'base.html' %}


{% block content %}
<div class="col-sm-10">
    <h3 class="text-white">Add New Post</h3>
 
    <div class="jumbotron jumbotron-fluid">
        <div class="container">
            <form method="POST">
                {% csrf_token %}
                <div class="row">
                    {{form.as_p}}
                    <button type="submit" class="btn btn-success">Send</button>
            </form>
        </div>
    </div>
    {% if messages %}
    {% for message in messages%}
    <span class="alert alert-success">{{message}}</span>
    {% endfor %}
    {% endif %}
</div>
{% endblock content %}

BlogIt/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">BlogIt</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">

        {% if request.user.is_authenticated %}
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'blogs:list-blogs'%}">Home</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'blogs:create-blog'%}">create blog</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'accounts:logout'%}">Logout</a>
        </li>
   
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:signup' %}">Signup</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
        </li>
        {% endif %}

      </ul>
    </div>
  </nav>